name: OrangeReader

options:
  minimumXcodeGenVersion: 2.38.0
  deploymentTarget:
    iOS: "17.0"

targets:
  Orange Reader:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    bundleId: com.ryanloomba.orangereader
    sources:
      - path: App
    resources:
      - path: App/Resources
    settings:
      TARGETED_DEVICE_FAMILY: 1
      CODE_SIGN_STYLE: Automatic
      PRODUCT_BUNDLE_IDENTIFIER: com.ryanloomba.orangereader
      GENERATE_INFOPLIST_FILE: NO
      INFOPLIST_FILE: App/Info.plist
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      PRODUCT_NAME: Orange Reader
    info:
      path: App/Info.plist
    dependencies:
      - package: SwiftReadability
        product: Readability

  OrangeReaderTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Tests
    dependencies:
      - target: Orange Reader

schemes:
  OrangeReader:
    build:
      targets:
        Orange Reader: all
    test:
      gatherCoverageData: true
      targets:
        - name: OrangeReaderTests
    run:
      config: Debug

packages:
  SwiftReadability:
    url: https://github.com/Ryu0118/swift-readability.git
    branch: main
